// Items 18, 19, 16 and 20 of the optimisation brief, GENERATED from the spec.
// A budget table and a rect listing maintained by hand are wrong within a
// week; these are regenerated by CI and diffed, like the blobs.
import { writeFileSync, readFileSync } from 'node:fs';
import { CLASSES, ANCHOR, SLOT } from '../spec/parts.js';
import { HEAD_SPECS, anchorsOf, CX, HEAD_TOP, EYE_W, EAR_W } from '../spec/anchors.js';
import { CUM, RAW, DENOM } from '../spec/weights.js';
import { encodeClass } from '../src/blob.js';
import { MOUTHS } from '../spec/parts.js';
import { mouthEligible, NECK_OF_BUILD, HEADWEAR_HAIR_FALLBACK } from '../src/render.js';
import { auditAll } from './silhouette-lib.mjs';

const A = new URL('..', import.meta.url);
const SLOT_NAME = Object.fromEntries(Object.entries(SLOT).map(([k, v]) => [v, k.toLowerCase()]));
const rectsOf = (c) => CLASSES[c].reduce((n, p) => n + (p.rects ?? []).length, 0);

// ---------------------------------------------------------------- item 18
let totalBytes = 0, totalRects = 0, totalParts = 0;
const rows = Object.keys(CLASSES).map((c) => {
  const bytes = encodeClass(CLASSES[c]).length;
  totalBytes += bytes; totalRects += rectsOf(c); totalParts += CLASSES[c].length;
  return { c, parts: CLASSES[c].length, rects: rectsOf(c), bytes,
    perPart: (bytes / CLASSES[c].length).toFixed(1), anchor: ANCHOR[c].at,
    mirror: ANCHOR[c].mirror ? 'yes' : '—' };
});
const pct = (n) => ((n / totalBytes) * 100).toFixed(1) + '%';

// v1, for the delta the brief asks the budget to justify
const V1 = { classes: 8, parts: 79, rects: 272, bytes: 1613 };

let md = `# The v2 atlas — budget, rect data and the anchor system

GENERATED by \`packages/art/tools/atlas-doc.mjs\`. Do not edit; run
\`node packages/art/tools/atlas-doc.mjs\` and commit the result. CI regenerates
and diffs this file, so a number here is a number that is actually deployed.

## 1 · Budget (item 18)

Every part is \`[x, y, w, h, paletteSlot]\`, five bytes on the wire, with x and
y biased by 32 so a part may legitimately draw outside the frame. A class blob
is \`[version][partCount][offset x 2N][parts…]\`, so a class costs
\`2 + 2N + sum(1 + 5R)\` bytes for N parts and R rects each.

| class | parts | rects | bytes | B/part | share | attaches to | mirrored |
|---|--:|--:|--:|--:|--:|---|---|
`;
for (const r of rows) {
  md += `| \`${r.c}\` | ${r.parts} | ${r.rects} | ${r.bytes} | ${r.perPart} | ${pct(r.bytes)} | ${r.anchor} | ${r.mirror} |\n`;
}
md += `| **total** | **${totalParts}** | **${totalRects}** | **${totalBytes}** | | | | |\n`;
md += `
Plus **${HEAD_SPECS.length * 4} bytes** of head geometry (\`HEAD_GEOM\`, four
integers per head) and ~${(2 * Object.values(CUM).reduce((n, c) => n + c.length, 0) + Object.keys(CUM).length * 3)} bytes
of cumulative weight tables, both inside \`FobalArtConstants\` rather than in a blob.

### What the extra bytes bought

| | v1 | v2 | delta |
|---|--:|--:|--:|
| classes | ${V1.classes} | ${Object.keys(CLASSES).length} | +${Object.keys(CLASSES).length - V1.classes} |
| parts | ${V1.parts} | ${totalParts} | ${totalParts - V1.parts >= 0 ? '+' : ''}${totalParts - V1.parts} |
| rects | ${V1.rects} | ${totalRects} | ${totalRects - V1.rects >= 0 ? '+' : ''}${totalRects - V1.rects} |
| atlas bytes | ${V1.bytes} | ${totalBytes} | ${totalBytes - V1.bytes >= 0 ? '+' : ''}${totalBytes - V1.bytes} (${((totalBytes / V1.bytes - 1) * 100).toFixed(1)}%) |

The brief's test was "a 3 KB atlas that looks dramatically better is a good
trade; 15 KB of invisible microvariation is not." This spends
**${totalBytes - V1.bytes} bytes** — ${((totalBytes / V1.bytes - 1) * 100).toFixed(0)}% — and buys five new classes
(per-head shading, ears, necks, builds, collars) plus per-head facial
architecture. The architecture itself is FREE: parts are authored once in
local space and translated onto the chosen head's anchors, so six skulls give
six faces from one stored copy of each feature.

It also spends bytes DOWNWARD where they were not earning: eyes 10 to
${CLASSES.EYES.length}, brows 8 to ${CLASSES.BROWS.length}, mouths 10 to ${CLASSES.MOUTHS.length},
headwear 10 to ${CLASSES.HEADWEAR.length}, hair 24 to ${CLASSES.HAIR.length}. The hair cut was not taste:
\`tools/silhouette-lib.mjs\` strips colour and measures every pair of masks, and
Cornrows and Undercut were **pixel-identical**.

## 2 · The anchor system (item 20)

Stored per head — four integers, ${HEAD_SPECS.length * 4} bytes total:

| head | width | chinY | eyeY | eyeGap |
|---|--:|--:|--:|--:|
`;
for (const h of HEAD_SPECS) md += `| ${h.name} | ${h.w} | ${h.bottom} | ${h.eyeY} | ${h.eyeGap} |\n`;
md += `
Derived on BOTH sides, never stored (\`spec/anchors.js\` and
\`contracts/src/art/FobalAnchors.sol\` compute these identically):

\`\`\`
headX      = ${CX} - (w >> 1)          browY      = eyeY - 3
noseX      = ${CX}   (faces are centred)  noseY      = eyeY + 2
leftEyeX   = ${CX} - (gap >> 1) - ${EYE_W}     mouthY     = chinY - 3
rightEyeX  = ${CX} + (gap >> 1) + (gap & 1)
earY       = eyeY                    earLeftX   = headX - 3
earRightX  = headX + w - 1           widthClass = w<=12 ? 0 : w<=14 ? 1 : 2
\`\`\`

\`mouthY = chinY - 3\` is derived rather than authored on purpose: pinning the
mouth a fixed distance above the chin is what lets ONE authored beard clear
the mouth on all six skulls.

Resolved anchors:

| head | headX | eyes | eyeY | browY | noseY | mouthY | chinY | ears | wc |
|---|--:|---|--:|--:|--:|--:|--:|---|--:|
`;
for (let i = 0; i < HEAD_SPECS.length; i++) {
  const a = anchorsOf(i);
  md += `| ${a.name} | ${a.headX} | ${a.leftEyeX}/${a.rightEyeX} | ${a.eyeY} | ${a.browY} | ${a.noseY} | ${a.mouthY} | ${a.chinY} | ${a.earLeftX}/${a.earRightX} | ${a.widthClass} |\n`;
}

// ---------------------------------------------------------------- item 16
md += `
## 3 · The compatibility matrix (item 16)

Deterministic and STABLE: no rule rerolls a lane. A restricted trait maps to a
defined alternative, so the same seed on a different head lands somewhere
predictable rather than in a different draw.

### Head width restricts mouth width

| width class | heads | eligible mouths |
|---|---|---|
`;
for (let wc = 0; wc < 3; wc++) {
  const heads = HEAD_SPECS.map((h, i) => [h, anchorsOf(i)]).filter(([, a]) => a.widthClass === wc).map(([h]) => h.name);
  md += `| ${wc} | ${heads.join(', ')} | ${mouthEligible(wc).map((i) => `${MOUTHS[i].name} (${MOUTHS[i].w}px)`).join(', ')} |\n`;
}
md += `
The lane picks WITHIN the eligible set, so every mouth stays reachable on the
heads that can carry it.

### Build decides neck

| build | ${CLASSES.BUILDS.map((b) => b.name).join(' | ')} |
|---|${CLASSES.BUILDS.map(() => '---').join('|')}|
| neck | ${NECK_OF_BUILD.map((n) => CLASSES.NECKS[n].name).join(' | ')} |

Derived, not drawn from its own lane — a slim player with a heavyweight's
throat reads as a bug, and this costs one fewer keccak.

### Hair under headwear

Headwear tagged \`covers\` maps hair through a fallback that is keyed by NAME
and idempotent (applying it twice equals applying it once):

| hair | becomes |
|---|---|
`;
CLASSES.HAIR.forEach((h, i) => {
  if (HEADWEAR_HAIR_FALLBACK[i] !== i) md += `| ${h.name} | ${CLASSES.HAIR[HEADWEAR_HAIR_FALLBACK[i]].name} |\n`;
});
md += `
Everything else is a fixed point and passes through unchanged.

### The remaining rules

| condition | resolution | why |
|---|---|---|
| bald + a band-tagged headwear | headwear becomes None | nothing to hold it on |
| full or long beard + Open mouth | mouth becomes Neutral | an open mouth inside a beard reads as a hole. Neutral, **not** Stern: Stern is 6px and illegal on a narrow skull, which is how a constraint pass quietly undoes the rule above it |
| full or long beard + Polo collar | collar becomes Crew | the beard covers the collar points |
| protruding ears + a covering headwear | ears become Normal | the hat would clip through them |

## 4 · Rect data (item 19)

Local space unless the class attaches \`absolute\`. Slot names map to
\`SLOT\` in \`spec/parts.js\`.

`;
for (const c of Object.keys(CLASSES)) {
  md += `### \`${c}\` — ${CLASSES[c].length} parts, attaches \`${ANCHOR[c].at}\`${ANCHOR[c].mirror ? ', mirrored' : ''}\n\n`;
  md += `| # | name | weight | rects \`[x, y, w, h, slot]\` |\n|--:|---|--:|---|\n`;
  CLASSES[c].forEach((p, i) => {
    const raw = RAW[c.toLowerCase()] ?? RAW[c.toLowerCase().replace(/s$/, '')];
    const wgt = raw ? `${((raw[i] / raw.reduce((a, b) => a + b, 0)) * 100).toFixed(1)}%` : '—';
    const rs = (p.rects ?? []).map((r) => `[${r[0]}, ${r[1]}, ${r[2]}, ${r[3]}, ${SLOT_NAME[r[4]]}]`).join(' ');
    md += `| ${i} | ${p.name} | ${wgt} | ${rs || '_(none)_'} |\n`;
  });
  md += '\n';
}

// ---------------------------------------------------------------- gates
md += `## 5 · Gates

| gate | what it measures | where |
|---|---|---|
| palette separation | CIE ΔE76; ramps on adjacent steps, categorical sets on all pairs | \`spec/palettes.js\` |
| 6:1 weight cap | no silhouette-bearing variant more than 6x another | \`spec/weights.js\` |
| silhouette separation | colour stripped, every pair of hair/headwear/beard masks compared | \`tools/silhouette-lib.mjs\` |
| blob round trip | every encoded part decodes back to its source rects | \`tools/gen-art.mjs\` |
| web field coverage | the browser data carries every authored field | \`tools/gen-art.mjs\` |
| byte parity | 64 fixtures, JS vs Solidity, hash for hash | \`contracts/test/unit/RendererParity.t.sol\` |
| full atlas decode | all ${totalRects} rects of all ${Object.keys(CLASSES).length} classes, on chain | \`contracts/test/unit/ArtLibrary.t.sol\` |
| EIP-170 | runtime size of every contract | \`forge build --sizes\` in CI |

Current silhouette audit:

`;
for (const rep of auditAll()) {
  const worst = [...rep.rows].sort((a, b) => a.delta - b.delta)[0];
  md += `- **${rep.label}**: ${rep.collisions.length ? '❌ ' + rep.collisions.join('; ') : `✅ clear — closest pair is ${worst.name} ~ ${worst.nearest} at Δ${worst.delta}px`}\n`;
}
md += '\n';

writeFileSync(new URL('../../docs/ART_ATLAS_V2.md', A), md);
console.log(`wrote docs/ART_ATLAS_V2.md — ${totalBytes} B atlas, ${totalParts} parts, ${totalRects} rects`);
