// art spec -> everything downstream, from ONE source.
//
//   packages/art/spec/*  ->  gen/blobs/*.bin   SSTORE2 payloads
//                            gen/blobs/*.hex   the same, for forge fixtures
//                            gen/manifest.json class table + gate numbers
//                            ../../contracts/src/art/FobalArtConstants.sol
//                            gen/parts.web.js  the web module (retires the
//                                              hand-maintained port in P5)
//
// gen/ is COMMITTED on purpose: these bytes are the contract between the JS
// reference renderer and the chain, CI verifies they are current by
// regenerating and diffing, and the Solidity tests read them as fixtures.
//
// Three implementations of this art exist today (Solidity, the web port, the
// golden client). Generating them removes the drift by construction.
import { mkdirSync, writeFileSync } from 'node:fs';
import { CLASSES, CANVAS, FACE, SLOT } from '../spec/parts.js';
import { CUM, RAW, DENOM, assertWeights } from '../spec/weights.js';
import { validatePalettes, SKIN, SKIN_BASE, HAIR, BG, ACCENT, INK, EYE_WHITE, IRIS } from '../spec/palettes.js';
import { encodeClass, decodePart, partCount, toHex, BIAS, BLOB_VERSION } from '../src/blob.js';
import { renderPlayer, seedOf, traitsOf, freeAgentKit } from '../src/render.js';
import { keccak_256 } from '@noble/hashes/sha3';

const A = new URL('..', import.meta.url);
const blobDir = new URL('./gen/blobs/', A);
const genDir = new URL('./gen/', A);
mkdirSync(blobDir, { recursive: true });
mkdirSync(genDir, { recursive: true });

const MAX_BLOB = 24575;            // EIP-170 minus the SSTORE2 STOP prefix
const fail = [];

// ---- gates that must hold before anything is written
const pal = validatePalettes();
if (!pal.pass) fail.push('palette separation gate failed');
const wts = assertWeights();
if (!wts.pass) fail.push(`weight gate failed: ${wts.bad.join('; ')}`);

// ---- encode every class, and prove the round trip immediately
const manifest = { version: BLOB_VERSION, canvas: CANVAS, bias: BIAS, denom: DENOM, classes: {} };
let totalBytes = 0;
for (const [name, parts] of Object.entries(CLASSES)) {
  const blob = encodeClass(parts);
  if (blob.length > MAX_BLOB) fail.push(`${name}: blob ${blob.length}B exceeds ${MAX_BLOB}B`);
  // round trip NOW: a blob that cannot be decoded back to its source rects
  // must never reach a deploy script
  if (partCount(blob) !== parts.length) fail.push(`${name}: partCount mismatch`);
  parts.forEach((part, i) => {
    const back = JSON.stringify(decodePart(blob, i));
    const want = JSON.stringify((part.rects ?? []).map(r => r.slice(0, 5)));
    if (back !== want) fail.push(`${name}[${i}] "${part.name}": round trip differs`);
  });
  writeFileSync(new URL(`./${name}.bin`, blobDir), blob);
  writeFileSync(new URL(`./${name}.hex`, blobDir), toHex(blob) + '\n');
  manifest.classes[name] = {
    parts: parts.length,
    bytes: blob.length,
    names: parts.map(p => p.name),
    cum: CUM[name.toLowerCase()] ?? null,
  };
  totalBytes += blob.length;
}

// ---- Solidity constants (indices + tables; NO art data — that lives in blobs)
const solLines = [
  '// SPDX-License-Identifier: MIT',
  'pragma solidity 0.8.28;',
  '',
  '/// @notice GENERATED by packages/art/tools/gen-art.mjs — do not edit.',
  '/// Class sizes, cumulative weight tables and palette values, kept in sync',
  '/// with the JS reference renderer by construction. The ART ITSELF lives in',
  '/// SSTORE2 blobs; nothing here is drawing data.',
  'library FobalArtConstants {',
  `    uint256 internal constant CANVAS = ${CANVAS};`,
  `    uint256 internal constant BIAS = ${BIAS};`,
  `    uint256 internal constant WEIGHT_DENOM = ${DENOM};`,
  `    uint8 internal constant BLOB_VERSION = ${BLOB_VERSION};`,
  '',
];
for (const [name, meta] of Object.entries(manifest.classes))
  solLines.push(`    uint256 internal constant ${name.toUpperCase()}_COUNT = ${meta.parts};`);
// headwear tag bitmasks — the constraint pass reads these, so they are
// generated from the same spec rather than restated by hand in Solidity
const maskOf = (tag) => CLASSES.HEADWEAR.reduce((m, p, i) => (p.tags ?? []).includes(tag) ? m | (1 << i) : m, 0);
solLines.push('', `    uint256 internal constant HEADWEAR_COVERS_MASK = ${maskOf('covers')};`,
  `    uint256 internal constant HEADWEAR_BAND_MASK = ${maskOf('band')};`);
solLines.push('');
for (const [k, cum] of Object.entries(CUM))
  solLines.push(`    function cum${k[0].toUpperCase()}${k.slice(1)}() internal pure returns (uint16[${cum.length}] memory) {`,
    `        return [${cum.map(v => `uint16(${v})`).join(', ')}];`, '    }');
solLines.push('');
const hexArr = (name, arr) =>
  `    bytes internal constant ${name} = hex"${arr.join('')}";`;
solLines.push(
  '    // palettes, packed 3 bytes per colour',
  hexArr('SKIN_BASE', SKIN_BASE),
  // shade/light are PRECOMPUTED here: JS mixes them with floating point and
  // Solidity must never attempt to reproduce that rounding
  hexArr('SKIN_SHADE', SKIN.map(t => t[1])), hexArr('SKIN_LIGHT', SKIN.map(t => t[2])),
  hexArr('HAIR_COLOR', HAIR), hexArr('BG_COLOR', BG), hexArr('ACCENT_COLOR', ACCENT),
  hexArr('IRIS_COLOR', IRIS),
  `    bytes3 internal constant INK = hex"${INK}";`,
  `    bytes3 internal constant EYE_WHITE = hex"${EYE_WHITE}";`,
  '}', '');
// written straight into the contracts tree — its only consumer. A second
// copy under gen/ would be one more thing that can silently drift.
writeFileSync(new URL('../../contracts/src/art/FobalArtConstants.sol', A), solLines.join('\n'));

// ---- the web module (generated; P5 deletes the hand-written port)
const web = [
  '// GENERATED by packages/art/tools/gen-art.mjs — do not edit.',
  '// The browser reads the SAME part data the chain stores, so the preview',
  '// can never drift from what gets minted.',
  `export const CANVAS = ${CANVAS};`,
  `export const FACE = ${JSON.stringify(FACE)};`,
  `export const SLOT = ${JSON.stringify(SLOT)};`,
  `export const CUM = ${JSON.stringify(CUM)};`,
  `export const PALETTES = ${JSON.stringify({ SKIN_BASE, HAIR, BG, ACCENT, IRIS, INK, EYE_WHITE })};`,
  `export const PARTS = ${JSON.stringify(
    Object.fromEntries(Object.entries(CLASSES).map(([k, v]) =>
      [k, v.map(p => ({ name: p.name, rects: p.rects ?? [], opacity: p.opacity ?? null, tags: p.tags ?? [] }))])))};`,
  '',
].join('\n');
writeFileSync(new URL('./parts.web.js', genDir), web);

// ---- parity fixtures: (dna, appearance) -> expected SVG hash. The forge
// test replays these through the Solidity renderer and compares hashes, so
// any divergence between the two implementations fails a build.
const FIXTURE_N = 64;
const fx = { dna: [], appearance: [], svgHash: [], traits: [] };
for (let i = 0; i < FIXTURE_N; i++) {
  const dnaBytes = keccak_256(new TextEncoder().encode(`fobal-fixture-${i}`));
  const dna = '0x' + [...dnaBytes].map(b => b.toString(16).padStart(2, '0')).join('');
  const appearance = (BigInt(dna) >> 96n) & 0xffffffffn;
  const svg = renderPlayer({ dna, appearance });
  const t = traitsOf(seedOf(dna, appearance));
  fx.dna.push(dna);
  fx.appearance.push(appearance.toString());
  fx.svgHash.push('0x' + [...keccak_256(new TextEncoder().encode(svg))].map(b => b.toString(16).padStart(2, '0')).join(''));
  fx.traits.push([t.head, t.skin, t.eyes, t.brows, t.nose, t.mouth, t.hair, t.hairColor, t.beard, t.headwear, t.bg, t.accent, t.iris].join(','));
}
mkdirSync(new URL('./gen/fixtures/', A), { recursive: true });
writeFileSync(new URL('./gen/fixtures/render.json', A), JSON.stringify(fx, null, 1));

manifest.totalBytes = totalBytes;
manifest.gates = { palettes: pal.pass, weights: wts.pass, maxBlobBytes: MAX_BLOB };
writeFileSync(new URL('./gen/manifest.json', A), JSON.stringify(manifest, null, 2));

console.log('class            parts   bytes');
for (const [k, m] of Object.entries(manifest.classes))
  console.log(`  ${k.padEnd(14)} ${String(m.parts).padStart(3)}  ${String(m.bytes).padStart(6)}`);
console.log(`  ${'TOTAL'.padEnd(14)}      ${String(totalBytes).padStart(6)} B of art data`);
console.log(`fixtures: ${FIXTURE_N} seeds -> gen/fixtures/render.json`);
console.log(`gates: palettes ${pal.pass ? 'PASS' : 'FAIL'} · weights ${wts.pass ? 'PASS' : 'FAIL'} · round-trip ${fail.length ? 'FAIL' : 'PASS'}`);
if (fail.length) { console.error('\nFAILURES:\n  ' + fail.join('\n  ')); process.exit(1); }
