// art spec -> everything downstream, from ONE source.
//
//   packages/art/spec/*  ->  gen/blobs/*.bin   SSTORE2 payloads
//                            gen/blobs/*.hex   the same, for forge fixtures
//                            gen/manifest.json class table + gate numbers
//                            ../../contracts/src/art/FobalArtConstants.sol
//                            gen/parts.web.js  the web module (retires the
//                                              hand-maintained port in P5)
//
// gen/ is COMMITTED on purpose: these bytes are the contract between the JS
// reference renderer and the chain, CI verifies they are current by
// regenerating and diffing, and the Solidity tests read them as fixtures.
//
// Three implementations of this art exist today (Solidity, the web port, the
// golden client). Generating them removes the drift by construction.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { CLASSES, CANVAS, FACE, SLOT } from '../spec/parts.js';
import { CUM, RAW, DENOM, assertWeights } from '../spec/weights.js';
import { validatePalettes, SKIN, SKIN_BASE, HAIR, BG, ACCENT, INK, EYE_WHITE, IRIS } from '../spec/palettes.js';
import { encodeClass, decodePart, partCount, toHex, BIAS, BLOB_VERSION } from '../src/blob.js';
import { renderPlayer, seedOf, traitsOf, freeAgentKit } from '../src/render.js';
import { keccak_256 } from '@noble/hashes/sha3';

const A = new URL('..', import.meta.url);
const blobDir = new URL('./gen/blobs/', A);
const genDir = new URL('./gen/', A);
mkdirSync(blobDir, { recursive: true });
mkdirSync(genDir, { recursive: true });

const MAX_BLOB = 24575;            // EIP-170 minus the SSTORE2 STOP prefix
const fail = [];

// ---- gates that must hold before anything is written
const pal = validatePalettes();
if (!pal.pass) fail.push('palette separation gate failed');
const wts = assertWeights();
if (!wts.pass) fail.push(`weight gate failed: ${wts.bad.join('; ')}`);

// ---- encode every class, and prove the round trip immediately
const manifest = { version: BLOB_VERSION, canvas: CANVAS, bias: BIAS, denom: DENOM, classes: {} };
let totalBytes = 0;
for (const [name, parts] of Object.entries(CLASSES)) {
  const blob = encodeClass(parts);
  if (blob.length > MAX_BLOB) fail.push(`${name}: blob ${blob.length}B exceeds ${MAX_BLOB}B`);
  // round trip NOW: a blob that cannot be decoded back to its source rects
  // must never reach a deploy script
  if (partCount(blob) !== parts.length) fail.push(`${name}: partCount mismatch`);
  parts.forEach((part, i) => {
    const back = JSON.stringify(decodePart(blob, i));
    const want = JSON.stringify((part.rects ?? []).map(r => r.slice(0, 5)));
    if (back !== want) fail.push(`${name}[${i}] "${part.name}": round trip differs`);
  });
  writeFileSync(new URL(`./${name}.bin`, blobDir), blob);
  writeFileSync(new URL(`./${name}.hex`, blobDir), toHex(blob) + '\n');
  manifest.classes[name] = {
    parts: parts.length,
    bytes: blob.length,
    names: parts.map(p => p.name),
    cum: CUM[name.toLowerCase()] ?? null,
  };
  totalBytes += blob.length;
}

// ---- Solidity constants (indices + tables; NO art data — that lives in blobs)
const solLines = [
  '// SPDX-License-Identifier: MIT',
  'pragma solidity 0.8.28;',
  '',
  '/// @notice GENERATED by packages/art/tools/gen-art.mjs — do not edit.',
  '/// Class sizes, cumulative weight tables and palette values, kept in sync',
  '/// with the JS reference renderer by construction. The ART ITSELF lives in',
  '/// SSTORE2 blobs; nothing here is drawing data.',
  'library FobalArtConstants {',
  `    uint256 internal constant CANVAS = ${CANVAS};`,
  `    uint256 internal constant BIAS = ${BIAS};`,
  `    uint256 internal constant WEIGHT_DENOM = ${DENOM};`,
  `    uint8 internal constant BLOB_VERSION = ${BLOB_VERSION};`,
  '',
];
for (const [name, meta] of Object.entries(manifest.classes))
  solLines.push(`    uint256 internal constant ${name.toUpperCase()}_COUNT = ${meta.parts};`);
// headwear tag bitmasks — the constraint pass reads these, so they are
// generated from the same spec rather than restated by hand in Solidity
const maskOf = (tag) => CLASSES.HEADWEAR.reduce((m, p, i) => (p.tags ?? []).includes(tag) ? m | (1 << i) : m, 0);
solLines.push('', `    uint256 internal constant HEADWEAR_COVERS_MASK = ${maskOf('covers')};`,
  `    uint256 internal constant HEADWEAR_BAND_MASK = ${maskOf('band')};`);
solLines.push('');
for (const [k, cum] of Object.entries(CUM))
  solLines.push(`    function cum${k[0].toUpperCase()}${k.slice(1)}() internal pure returns (uint16[${cum.length}] memory) {`,
    `        return [${cum.map(v => `uint16(${v})`).join(', ')}];`, '    }');
solLines.push('');
const hexArr = (name, arr) =>
  `    bytes internal constant ${name} = hex"${arr.join('')}";`;
solLines.push(
  '    // palettes, packed 3 bytes per colour',
  hexArr('SKIN_BASE', SKIN_BASE),
  // shade/light are PRECOMPUTED here: JS mixes them with floating point and
  // Solidity must never attempt to reproduce that rounding
  hexArr('SKIN_SHADE', SKIN.map(t => t[1])), hexArr('SKIN_LIGHT', SKIN.map(t => t[2])),
  hexArr('HAIR_COLOR', HAIR), hexArr('BG_COLOR', BG), hexArr('ACCENT_COLOR', ACCENT),
  hexArr('IRIS_COLOR', IRIS),
  `    bytes3 internal constant INK = hex"${INK}";`,
  `    bytes3 internal constant EYE_WHITE = hex"${EYE_WHITE}";`,
  '}', '');
// written straight into the contracts tree — its only consumer. A second
// copy under gen/ would be one more thing that can silently drift.
writeFileSync(new URL('../../contracts/src/art/FobalArtConstants.sol', A), solLines.join('\n'));

// ---- the web avatar module. GENERATED, and self-contained: apps/web ships
// as plain ES modules with no bundler, so the keccak the chain hashes with is
// inlined rather than imported. Replacing the hand-written port is the point
// of P5 — a "faithful port" maintained by hand drifts, and did.
const web = [
  '// GENERATED by packages/art/tools/gen-art.mjs — do not edit.',
  '// The browser reads the SAME part data the chain stores, so the preview',
  '// can never drift from what gets minted.',
  `export const CANVAS = ${CANVAS};`,
  `export const FACE = ${JSON.stringify(FACE)};`,
  `export const SLOT = ${JSON.stringify(SLOT)};`,
  `export const CUM = ${JSON.stringify(CUM)};`,
  `export const PALETTES = ${JSON.stringify({ SKIN_BASE, HAIR, BG, ACCENT, IRIS, INK, EYE_WHITE })};`,
  `export const PARTS = ${JSON.stringify(
    Object.fromEntries(Object.entries(CLASSES).map(([k, v]) =>
      [k, v.map(p => ({ name: p.name, rects: p.rects ?? [], opacity: p.opacity ?? null, tags: p.tags ?? [] }))])))};`,
  '',
].join('\n');
writeFileSync(new URL('./parts.web.js', genDir), web);

// the runnable web renderer: data + keccak + the same render logic, emitted
// straight into apps/web so the preview and the chain cannot diverge
const keccakSrc = readFileSync(new URL('./src/keccak-web.js', A), 'utf8')
  .replace(/^export /gm, '');
const renderSrc = readFileSync(new URL('./src/render.js', A), 'utf8');
// lift the body of the reference renderer, swapping its module imports for
// the inlined data above — the logic itself is copied verbatim, never retyped
const renderBody = renderSrc
  .split('\n')
  // drop module plumbing: imports, and re-exports of things that are inlined
  // above as plain consts. The RENDER LOGIC below is copied verbatim.
  .filter(l => !l.startsWith('import ') && !l.startsWith('export {'))
  .join('\n')
  .replace(/^export /gm, '');

const avatarJs = [
  '// GENERATED by packages/art/tools/gen-art.mjs — DO NOT EDIT.',
  '//',
  '// The browser draws players from the SAME part data, palettes, weight',
  '// tables and render logic the chain uses, with the same keccak. This file',
  '// replaces a hand-maintained port that had silently diverged (a goalkeeper',
  '// kit the chain never had, and a 24-bit appearance mask that hid every',
  '// accessory). Regenerate with: node packages/art/tools/gen-art.mjs',
  '',
  '// ---- keccak-256 (verified against @noble/hashes in packages/art/test)',
  keccakSrc,
  'const keccak_256 = keccak256;',
  '',
  '// ---- generated art data',
  `const SKIN_BASE = ${JSON.stringify(SKIN_BASE)};`,
  `const SKIN = ${JSON.stringify(SKIN)};`,
  `const HAIR_COL = ${JSON.stringify(HAIR)};`,
  `const BG = ${JSON.stringify(BG)};`,
  `const ACCENT = ${JSON.stringify(ACCENT)};`,
  `const INK = ${JSON.stringify(INK)};`,
  `const EYE_WHITE = ${JSON.stringify(EYE_WHITE)};`,
  `const IRIS = ${JSON.stringify(IRIS)};`,
  `const CUM = ${JSON.stringify(CUM)};`,
  `const DENOM = ${DENOM};`,
  `const CANVAS = ${CANVAS};`,
  `const FACE = ${JSON.stringify(FACE)};`,
  `const SLOT = ${JSON.stringify(SLOT)};`,
  ...Object.entries(CLASSES).map(([k, v]) =>
    `const ${k} = ${JSON.stringify(v.map(p => ({ name: p.name, rects: p.rects ?? [], tags: p.tags ?? [] })))};`),
  'const pickFromCum = (cum, r) => { for (let i = 0; i < cum.length; i++) if (r < cum[i]) return i; return cum.length - 1; };',
  '',
  '// ---- the reference renderer, verbatim',
  renderBody,
  '',
  '// ---- the public API. Two names, because the distinction matters:',
  '// what the CHAIN renders, and what a club kit would look like.',
  '',
  '/** Exactly what tokenURI returns for this identity today (free agent). */',
  'export function avatarSvgOnchain({ dna, appearance, position = 2 }) {',
  '  return renderPlayer({ dna, appearance, position });',
  '}',
  '',
  '/** The same identity wearing a specific club kit. */',
  'export function avatarSvgDressed({ dna, appearance, position = 2 }, kit) {',
  '  return renderPlayer({ dna, appearance, kit, position });',
  '}',
  '',
  'export function avatarDataUri(p, kit) {',
  '  const svg = kit ? avatarSvgDressed(p, kit) : avatarSvgOnchain(p);',
  "  return 'data:image/svg+xml;utf8,' + encodeURIComponent(svg);",
  '}',
  '',
  'export { traitsOf, seedOf, freeAgentKit, CANVAS };',
  '',
].join('\n');
writeFileSync(new URL('../../apps/web/public/js/avatar.js', A), avatarJs);

// ---- parity fixtures: (dna, appearance) -> expected SVG hash. The forge
// test replays these through the Solidity renderer and compares hashes, so
// any divergence between the two implementations fails a build.
const FIXTURE_N = 64;
const hashOf = (str) => '0x' + [...keccak_256(new TextEncoder().encode(str))]
  .map(b => b.toString(16).padStart(2, '0')).join('');
const fx = {
  dna: [], appearance: [], svgHash: [], traits: [],
  // an EXPLICIT kit per fixture, so P4's club-kit path is proven byte-exact
  // too — not just the free-agent one
  kitPrimary: [], kitSecondary: [], kitAccent: [], kitPattern: [], svgKitHash: [],
};
for (let i = 0; i < FIXTURE_N; i++) {
  const dnaBytes = keccak_256(new TextEncoder().encode(`fobal-fixture-${i}`));
  const dna = '0x' + [...dnaBytes].map(b => b.toString(16).padStart(2, '0')).join('');
  const appearance = (BigInt(dna) >> 96n) & 0xffffffffn;
  const t = traitsOf(seedOf(dna, appearance));
  fx.dna.push(dna);
  fx.appearance.push(appearance.toString());
  fx.svgHash.push(hashOf(renderPlayer({ dna, appearance })));
  fx.traits.push([t.head, t.skin, t.eyes, t.brows, t.nose, t.mouth, t.hair, t.hairColor, t.beard, t.headwear, t.bg, t.accent, t.iris].join(','));
  // deterministic club kit, spanning every pattern across the fixture set
  const kh = BigInt(hashOf(`kit-${i}`));
  const kit = {
    primary: Number((kh >> 8n) & 0xffffffn).toString(16).padStart(6, '0'),
    secondary: Number((kh >> 40n) & 0xffffffn).toString(16).padStart(6, '0'),
    accent: Number((kh >> 72n) & 0xffffffn).toString(16).padStart(6, '0'),
    pattern: i % 7,
  };
  fx.kitPrimary.push(String(parseInt(kit.primary, 16)));
  fx.kitSecondary.push(String(parseInt(kit.secondary, 16)));
  fx.kitAccent.push(String(parseInt(kit.accent, 16)));
  fx.kitPattern.push(String(kit.pattern));
  fx.svgKitHash.push(hashOf(renderPlayer({ dna, appearance, kit })));
}
mkdirSync(new URL('./gen/fixtures/', A), { recursive: true });
writeFileSync(new URL('./gen/fixtures/render.json', A), JSON.stringify(fx, null, 1));

manifest.totalBytes = totalBytes;
manifest.gates = { palettes: pal.pass, weights: wts.pass, maxBlobBytes: MAX_BLOB };
writeFileSync(new URL('./gen/manifest.json', A), JSON.stringify(manifest, null, 2));

console.log('class            parts   bytes');
for (const [k, m] of Object.entries(manifest.classes))
  console.log(`  ${k.padEnd(14)} ${String(m.parts).padStart(3)}  ${String(m.bytes).padStart(6)}`);
console.log(`  ${'TOTAL'.padEnd(14)}      ${String(totalBytes).padStart(6)} B of art data`);
console.log(`fixtures: ${FIXTURE_N} seeds -> gen/fixtures/render.json`);
console.log(`gates: palettes ${pal.pass ? 'PASS' : 'FAIL'} · weights ${wts.pass ? 'PASS' : 'FAIL'} · round-trip ${fail.length ? 'FAIL' : 'PASS'}`);
if (fail.length) { console.error('\nFAILURES:\n  ' + fail.join('\n  ')); process.exit(1); }
