// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

/// @notice GENERATED by packages/art/tools/gen-art.mjs — do not edit.
/// Class sizes, cumulative weight tables and palette values, kept in sync
/// with the JS reference renderer by construction. The ART ITSELF lives in
/// SSTORE2 blobs; nothing here is drawing data.
library FobalArtConstants {
    uint256 internal constant CANVAS = 32;
    uint256 internal constant BIAS = 32;
    uint256 internal constant WEIGHT_DENOM = 4096;
    uint8 internal constant BLOB_VERSION = 1;

    uint256 internal constant HEADS_COUNT = 6;
    uint256 internal constant SHADING_COUNT = 6;
    uint256 internal constant EARS_COUNT = 3;
    uint256 internal constant EYES_COUNT = 6;
    uint256 internal constant BROWS_COUNT = 6;
    uint256 internal constant NOSES_COUNT = 7;
    uint256 internal constant MOUTHS_COUNT = 7;
    uint256 internal constant BEARDS_COUNT = 8;
    uint256 internal constant HAIR_COUNT = 21;
    uint256 internal constant HEADWEAR_COUNT = 6;
    uint256 internal constant NECKS_COUNT = 3;
    uint256 internal constant BUILDS_COUNT = 4;
    uint256 internal constant COLLARS_COUNT = 4;

    uint256 internal constant ART_CLASS_COUNT = 13;

    /// @notice Every art class, in blob order. Deploy scripts and tests
    /// MUST iterate this rather than restating it. Dynamic on purpose: a
    /// library constant is not accepted as a fixed-array length, and a
    /// hand-written length is the very thing this function removes.
    function classNames() internal pure returns (bytes32[] memory out) {
        out = new bytes32[](13);
        out[0] = bytes32("HEADS");
        out[1] = bytes32("SHADING");
        out[2] = bytes32("EARS");
        out[3] = bytes32("EYES");
        out[4] = bytes32("BROWS");
        out[5] = bytes32("NOSES");
        out[6] = bytes32("MOUTHS");
        out[7] = bytes32("BEARDS");
        out[8] = bytes32("HAIR");
        out[9] = bytes32("HEADWEAR");
        out[10] = bytes32("NECKS");
        out[11] = bytes32("BUILDS");
        out[12] = bytes32("COLLARS");
    }

    uint256 internal constant HEADWEAR_COVERS_MASK = 56;
    uint256 internal constant HEADWEAR_BAND_MASK = 6;

    // ---- anchor system
    uint256 internal constant CX = 16;
    uint256 internal constant HEAD_TOP = 4;
    uint256 internal constant EYE_W = 4;
    uint256 internal constant EAR_W = 4;
    /// @dev 4 bytes per head: width, chinY, eyeY, eyeGap. Everything else
    /// (headX, brow/nose/mouth/ear lines, eye x, width class) is DERIVED.
    bytes internal constant HEAD_GEOM = hex"0e150c030c160c020f140c0410150c0510160b050f150b04";
    /// @dev one byte per class, in blob order: HEADS, SHADING, EARS, EYES, BROWS, NOSES, MOUTHS, BEARDS, HAIR, HEADWEAR, NECKS, BUILDS, COLLARS
    bytes internal constant CLASS_ATTACH = hex"00000301020405060707000000";
    /// @dev mirror-box width per class; 0 means the part is drawn once
    bytes internal constant CLASS_MIRROR = hex"00000404040000000000000000";
    /// @dev skull-clamp margin per class; 0 means the class is never clipped
    bytes internal constant CLASS_CLAMP = hex"00000000000000000202000000";

    // ---- weight tables: 2 bytes per entry, indexed by CLS_* below
    uint256 internal constant CLS_HEAD = 0;
    uint256 internal constant CLS_EYES = 1;
    uint256 internal constant CLS_BROWS = 2;
    uint256 internal constant CLS_NOSE = 3;
    uint256 internal constant CLS_MOUTH = 4;
    uint256 internal constant CLS_EARS = 5;
    uint256 internal constant CLS_BUILD = 6;
    uint256 internal constant CLS_COLLAR = 7;
    uint256 internal constant CLS_HAIR = 8;
    uint256 internal constant CLS_BEARD = 9;
    uint256 internal constant CLS_HEADWEAR = 10;
    uint256 internal constant CLS_HAIRCOLOR = 11;
    uint256 internal constant CLS_SKIN = 12;
    uint256 internal constant CLS_BG = 13;
    uint256 internal constant CLS_ACCENT = 14;
    uint256 internal constant CLS_IRIS = 15;
    uint256 internal constant CLS_COUNT = 16;
    bytes internal constant CUM_DATA = hex"02ae055808020aac0d56100002ae055808020aac0d56100002ae055808020aac0d561000024a049306dc09250b6e0db71000024a049306dc09250b6e0db7100005dd0ccd1000039908ce0d34100004a308d80ca21000006a017302a203ab04a7057b066a0766082008bf095109bb0a670b060b8a0c6c0d260db80e720f39100004270669081a09b30b040d160edf10000b780ccb0dd70e9b0f2a1000028504d506f308e00a9c0c260d7f0ea7100002000400060008000a000c000e00100002000400060008000a000c000e00100002000400060008000a000c000e001000040008000c001000";
    bytes internal constant CUM_OFFSET = hex"00000006000c00120019002000230027002b00400048004e0057005f0067006f";
    bytes internal constant CUM_LEN = hex"06060607070304041508060908080804";

    /// @notice The cumulative table for one class, unpacked.
    function cumOf(uint256 cls) internal pure returns (uint16[] memory out) {
        bytes memory off = CUM_OFFSET;
        bytes memory len = CUM_LEN;
        bytes memory data = CUM_DATA;
        uint256 start = (uint256(uint8(off[cls * 2])) << 8) | uint256(uint8(off[cls * 2 + 1]));
        uint256 n = uint256(uint8(len[cls]));
        out = new uint16[](n);
        for (uint256 k; k < n; ++k) {
            uint256 j = (start + k) * 2;
            out[k] = uint16((uint256(uint8(data[j])) << 8) | uint256(uint8(data[j + 1])));
        }
    }

    // ---- deterministic compatibility tables (item 16). Generated from the
    // reference renderer, never restated by hand.
    bytes internal constant HAIR_FALLBACK = hex"0001020304050607070101010d0d0e031111121302";
    bytes internal constant NECK_OF_BUILD = hex"00010102";
    /// @dev mouths a head of each width class may wear, concatenated
    bytes internal constant MOUTH_ELIG = hex"000406000204050600010203040506";
    bytes internal constant MOUTH_ELIG_LEN = hex"030507";
    /// @dev x and width of each build's torso box, so the kit composer can
    /// place a pattern from pure geometry without ever seeing a trait.
    bytes internal constant BUILD_TORSO = hex"07120516031a021c";

    // palettes, packed 3 bytes per colour
    bytes internal constant SKIN_BASE = hex"fedfd1eac0aed3a28dba86719e6c59805444613f32432a23";
    bytes internal constant SKIN_SHADE = hex"bea295b08c7ca077658f64527b52416641325132253c231b";
    bytes internal constant SKIN_LIGHT = hex"fee7daf1d3c4e2bfaed2ad9cc09c8cac8d7f987f73857169";
    bytes internal constant HAIR_COLOR = hex"141010312d29514b42746c5e988f7bbeb399e6d9b8b8481f9aa3ab";
    bytes internal constant BG_COLOR = hex"281a1e6da3989c6d73335b754c56369296ba9d9370002312";
    bytes internal constant ACCENT_COLOR = hex"e8e2d41b1b1fd8342ce0a02a2f8f4e2f6fd08a5cf6e8712f";
    bytes internal constant IRIS_COLOR = hex"3b2a1c2a3d523d52405a4632";
    bytes3 internal constant INK = hex"0f0b09";
    bytes3 internal constant EYE_WHITE = hex"f4f1ea";
}
