// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

/// @notice GENERATED by packages/art/tools/gen-art.mjs — do not edit.
/// Class sizes, cumulative weight tables and palette values, kept in sync
/// with the JS reference renderer by construction. The ART ITSELF lives in
/// SSTORE2 blobs; nothing here is drawing data.
library FobalArtConstants {
    uint256 internal constant CANVAS = 32;
    uint256 internal constant BIAS = 32;
    uint256 internal constant WEIGHT_DENOM = 4096;
    uint8 internal constant BLOB_VERSION = 1;

    uint256 internal constant HEADS_COUNT = 6;
    uint256 internal constant EYES_COUNT = 10;
    uint256 internal constant BROWS_COUNT = 8;
    uint256 internal constant NOSES_COUNT = 3;
    uint256 internal constant MOUTHS_COUNT = 10;
    uint256 internal constant BEARDS_COUNT = 8;
    uint256 internal constant HAIR_COUNT = 24;
    uint256 internal constant HEADWEAR_COUNT = 10;

    uint256 internal constant HEADWEAR_COVERS_MASK = 760;
    uint256 internal constant HEADWEAR_BAND_MASK = 262;

    function cumHead() internal pure returns (uint16[6] memory) {
        return [uint16(686), uint16(1368), uint16(2050), uint16(2732), uint16(3414), uint16(4096)];
    }
    function cumEyes() internal pure returns (uint16[10] memory) {
        return [uint16(415), uint16(824), uint16(1233), uint16(1642), uint16(2051), uint16(2460), uint16(2869), uint16(3278), uint16(3687), uint16(4096)];
    }
    function cumBrows() internal pure returns (uint16[8] memory) {
        return [uint16(512), uint16(1024), uint16(1536), uint16(2048), uint16(2560), uint16(3072), uint16(3584), uint16(4096)];
    }
    function cumNose() internal pure returns (uint16[3] memory) {
        return [uint16(1366), uint16(2731), uint16(4096)];
    }
    function cumMouth() internal pure returns (uint16[10] memory) {
        return [uint16(415), uint16(824), uint16(1233), uint16(1642), uint16(2051), uint16(2460), uint16(2869), uint16(3278), uint16(3687), uint16(4096)];
    }
    function cumHair() internal pure returns (uint16[24] memory) {
        return [uint16(93), uint16(198), uint16(408), uint16(641), uint16(906), uint16(1139), uint16(1360), uint16(1546), uint16(1756), uint16(1977), uint16(2140), uint16(2280), uint16(2408), uint16(2501), uint16(2652), uint16(2792), uint16(2908), uint16(3106), uint16(3269), uint16(3397), uint16(3560), uint16(3735), uint16(3921), uint16(4096)];
    }
    function cumBeard() internal pure returns (uint16[8] memory) {
        return [uint16(1063), uint16(1641), uint16(2074), uint16(2483), uint16(2820), uint16(3350), uint16(3807), uint16(4096)];
    }
    function cumHeadwear() internal pure returns (uint16[10] memory) {
        return [uint16(2574), uint16(2830), uint16(3029), uint16(3257), uint16(3428), uint16(3542), uint16(3670), uint16(3769), uint16(3925), uint16(4096)];
    }
    function cumHairColor() internal pure returns (uint16[9] memory) {
        return [uint16(645), uint16(1237), uint16(1779), uint16(2272), uint16(2716), uint16(3110), uint16(3455), uint16(3751), uint16(4096)];
    }
    function cumSkin() internal pure returns (uint16[8] memory) {
        return [uint16(512), uint16(1024), uint16(1536), uint16(2048), uint16(2560), uint16(3072), uint16(3584), uint16(4096)];
    }
    function cumBg() internal pure returns (uint16[8] memory) {
        return [uint16(512), uint16(1024), uint16(1536), uint16(2048), uint16(2560), uint16(3072), uint16(3584), uint16(4096)];
    }
    function cumAccent() internal pure returns (uint16[8] memory) {
        return [uint16(512), uint16(1024), uint16(1536), uint16(2048), uint16(2560), uint16(3072), uint16(3584), uint16(4096)];
    }
    function cumIris() internal pure returns (uint16[4] memory) {
        return [uint16(1024), uint16(2048), uint16(3072), uint16(4096)];
    }

    // palettes, packed 3 bytes per colour
    bytes internal constant SKIN_BASE = hex"fedfd1eac0aed3a28dba86719e6c59805444613f32432a23";
    bytes internal constant SKIN_SHADE = hex"bea295b08c7ca077658f64527b52416641325132253c231b";
    bytes internal constant SKIN_LIGHT = hex"fee7daf1d3c4e2bfaed2ad9cc09c8cac8d7f987f73857169";
    bytes internal constant HAIR_COLOR = hex"141010312d29514b42746c5e988f7bbeb399e6d9b8b8481f9aa3ab";
    bytes internal constant BG_COLOR = hex"281a1e6da3989c6d73335b754c56369296ba9d9370002312";
    bytes internal constant ACCENT_COLOR = hex"e8e2d41b1b1fd8342ce0a02a2f8f4e2f6fd08a5cf6e8712f";
    bytes internal constant IRIS_COLOR = hex"3b2a1c2a3d523d52405a4632";
    bytes3 internal constant INK = hex"0f0b09";
    bytes3 internal constant EYE_WHITE = hex"f4f1ea";
}
