// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {FobalArtConstants as K} from "../../src/art/FobalArtConstants.sol";
import {FobalArtLibrary} from "../../src/FobalArtLibrary.sol";
import {SSTORE2} from "../../src/libraries/SSTORE2.sol";
import {IAccessControl} from "@openzeppelin/contracts/access/IAccessControl.sol";

/// THE P2 CLAIM: the bytes generated by packages/art/tools/gen-art.mjs decode
/// on-chain to exactly the rects the JS reference renderer draws from. The
/// fixtures read here are the SAME FILES the browser preview will load, so a
/// drift between preview and chain becomes a failing test rather than a
/// surprise after minting.
contract ArtLibraryTest is Test {
    FobalArtLibrary internal lib;
    address internal admin = makeAddr("admin");
    address internal bob = makeAddr("bob");

    bytes32 constant HAIR = bytes32("HAIR");
    bytes32 constant NOSES = bytes32("NOSES");

    function setUp() public {
        lib = new FobalArtLibrary(admin);
    }

    function _blob(string memory className) internal view returns (bytes memory) {
        string memory hexStr = vm.readFile(
            string.concat(vm.projectRoot(), "/../packages/art/gen/blobs/", className, ".hex")
        );
        return vm.parseBytes(vm.replace(hexStr, "\n", ""));
    }

    function _name(bytes32 k) internal pure returns (string memory) {
        uint256 n;
        while (n < 32 && k[n] != 0) ++n;
        bytes memory b = new bytes(n);
        for (uint256 i; i < n; ++i) b[i] = k[i];
        return string(b);
    }

    function _install(bytes32 key, string memory className) internal returns (bytes memory blob) {
        blob = _blob(className);
        vm.prank(admin);
        lib.setClass(key, blob);
    }

    // ------------------------------------------------- the cross-language proof

    /// EVERY rect of EVERY class, replayed from the generated fixture. This
    /// replaced three hand-picked spot checks that asserted literal counts and
    /// coordinates — they broke the moment the atlas grew, and while they were
    /// broken they were proving nothing about the other twelve classes.
    function test_decodesGeneratedBytesToTheExactJsRects() public {
        bytes32[] memory names = K.classNames();
        for (uint256 i; i < names.length; ++i) {
            _install(names[i], _name(names[i]));
        }

        string memory json = vm.readFile(string.concat(vm.projectRoot(), "/../packages/art/gen/fixtures/rects.json"));
        string[] memory fxClass = vm.parseJsonStringArray(json, ".className");
        uint256[] memory fxPart = vm.parseJsonUintArray(json, ".partIndex");
        int256[] memory fxX = vm.parseJsonIntArray(json, ".x");
        int256[] memory fxY = vm.parseJsonIntArray(json, ".y");
        uint256[] memory fxW = vm.parseJsonUintArray(json, ".w");
        uint256[] memory fxH = vm.parseJsonUintArray(json, ".h");
        uint256[] memory fxSlot = vm.parseJsonUintArray(json, ".slot");
        uint256[] memory fxCount = vm.parseJsonUintArray(json, ".partCount");

        assertEq(fxCount.length, names.length, "fixture covers every class");
        for (uint256 i; i < names.length; ++i) {
            assertEq(uint256(lib.partCount(names[i])), fxCount[i], _name(names[i]));
        }

        // walk the flattened fixture, re-decoding a part only when it changes
        uint256 k;
        for (uint256 i; i < names.length; ++i) {
            string memory cn = _name(names[i]);
            for (uint8 p; p < lib.partCount(names[i]); ++p) {
                FobalArtLibrary.Rect[] memory rects = lib.part(names[i], p);
                for (uint256 r; r < rects.length; ++r) {
                    assertLt(k, fxX.length, "fixture ran out of rects");
                    assertEq(fxClass[k], cn, "class order");
                    assertEq(fxPart[k], uint256(p), "part order");
                    assertEq(int256(rects[r].x), fxX[k], string.concat(cn, " x"));
                    assertEq(int256(rects[r].y), fxY[k], string.concat(cn, " y"));
                    assertEq(uint256(rects[r].w), fxW[k], string.concat(cn, " w"));
                    assertEq(uint256(rects[r].h), fxH[k], string.concat(cn, " h"));
                    assertEq(uint256(rects[r].slot), fxSlot[k], string.concat(cn, " slot"));
                    ++k;
                }
            }
        }
        assertEq(k, fxX.length, "every generated rect must be accounted for");
        assertGt(k, 250, "the atlas must not have silently shrunk to nothing");
    }

    /// Negative coordinates must survive the bias — parts legitimately draw
    /// outside the frame, and an unsigned decode would wrap them.
    function test_negativeCoordinatesSurviveTheBias() public {
        _install(bytes32("HAIR"), "HAIR");
        bool sawNegative;
        for (uint8 p; p < lib.partCount(bytes32("HAIR")); ++p) {
            FobalArtLibrary.Rect[] memory rects = lib.part(bytes32("HAIR"), p);
            for (uint256 r; r < rects.length; ++r) {
                if (rects[r].x < 0 || rects[r].y < 0) sawNegative = true;
            }
        }
        assertTrue(sawNegative, "hair draws above and beside the skull; the bias must carry that");
    }

    function test_emptyPartDecodesToNoRects() public {
        _install(HAIR, "HAIR");
        assertEq(lib.part(HAIR, 0).length, 0, "HAIR[0] is Bald: no rects, not a revert");
    }

    function test_decodesASecondClassIndependently() public {
        _install(NOSES, "NOSES");
        assertEq(uint256(lib.partCount(NOSES)), K.NOSES_COUNT, "count must track the generated constant");
        // whatever the atlas holds, a second class must decode on its own
        // rather than inheriting the first one's offsets
        FobalArtLibrary.Rect[] memory first = lib.part(NOSES, 0);
        FobalArtLibrary.Rect[] memory last = lib.part(NOSES, uint8(K.NOSES_COUNT - 1));
        assertGt(first.length, 0);
        assertGt(last.length, 0);
        assertTrue(
            first.length != last.length || first[0].x != last[0].x || first[0].y != last[0].y,
            "two different noses must not decode identically"
        );
    }

    /// every part of every generated class must decode without reverting and
    /// stay inside sane bounds — the sweep that catches an encoder change
    function test_everyPartOfEveryClassDecodesInBounds() public {
        string[8] memory names =
            ["HEADS", "EYES", "BROWS", "NOSES", "MOUTHS", "BEARDS", "HAIR", "HEADWEAR"];
        uint256 totalRects;
        for (uint256 c; c < names.length; ++c) {
            bytes32 key = bytes32(bytes(names[c]));
            _install(key, names[c]);
            uint8 n = lib.partCount(key);
            assertGt(n, 0, names[c]);
            for (uint8 i; i < n; ++i) {
                FobalArtLibrary.Rect[] memory rs = lib.part(key, i);
                for (uint256 r; r < rs.length; ++r) {
                    assertGe(rs[r].x, int16(-32));
                    assertLe(rs[r].x, int16(64));
                    assertGe(rs[r].y, int16(-32));
                    assertLe(rs[r].y, int16(64));
                    assertGt(rs[r].w, uint8(0));
                    assertGt(rs[r].h, uint8(0));
                    assertLt(rs[r].slot, uint8(16));
                    ++totalRects;
                }
            }
        }
        emit log_named_uint("rects decoded across the whole atlas", totalRects);
        assertGt(totalRects, 200);
    }

    // ------------------------------------------------------------ storage

    function test_sstore2_roundTripsExactBytes() public {
        bytes memory blob = _blob("HAIR");
        address ptr = SSTORE2.write(blob);
        assertEq(SSTORE2.payloadLength(ptr), blob.length, "payload length");
        assertEq(keccak256(SSTORE2.read(ptr)), keccak256(blob), "bytes must survive verbatim");
        // and a window read matches the same window of the source
        bytes memory slice = SSTORE2.readSlice(ptr, 2, 8);
        for (uint256 i; i < 8; ++i) {
            assertEq(uint8(slice[i]), uint8(blob[2 + i]));
        }
    }

    function test_blobIsNotExecutable() public {
        address ptr = SSTORE2.write(_blob("NOSES"));
        (bool ok,) = ptr.call("");
        assertTrue(ok, "the STOP prefix means a call halts harmlessly");
    }

    // ------------------------------------------------- permanence + access

    function test_sealMakesAClassPermanent() public {
        _install(HAIR, "HAIR");
        vm.prank(admin);
        lib.seal(HAIR);
        assertTrue(lib.classInfo(HAIR).sealed_);
        vm.expectRevert(abi.encodeWithSelector(FobalArtLibrary.AlreadySealed.selector, HAIR));
        vm.prank(admin);
        lib.setClass(HAIR, _blob("HAIR"));
    }

    function test_unsealedClassCanBeRepointed_soReadBackHappensBeforeSealing() public {
        bytes memory blob = _blob("HAIR");
        vm.startPrank(admin);
        address first = lib.setClass(HAIR, blob);
        address second = lib.setClass(HAIR, blob);
        vm.stopPrank();
        assertTrue(first != second, "a fresh blob is deployed each time");
        assertEq(lib.classInfo(HAIR).pointer, second);
    }

    function test_onlyArtAdminCanWrite() public {
        bytes memory blob = _blob("NOSES");
        bytes memory err = abi.encodeWithSelector(
            IAccessControl.AccessControlUnauthorizedAccount.selector, bob, lib.ART_ADMIN_ROLE()
        );
        vm.startPrank(bob);
        vm.expectRevert(err);
        lib.setClass(NOSES, blob);
        vm.expectRevert(err);
        lib.seal(NOSES);
        vm.stopPrank();
    }

    function test_rejectsForeignBlobVersions() public {
        vm.startPrank(admin);
        vm.expectRevert(abi.encodeWithSelector(FobalArtLibrary.BadVersion.selector, uint8(9)));
        lib.setClass(HAIR, hex"0903");
        vm.stopPrank();
    }

    function test_unknownClassAndRangeErrors() public {
        vm.expectRevert(abi.encodeWithSelector(FobalArtLibrary.UnknownClass.selector, bytes32("NOPE")));
        lib.part(bytes32("NOPE"), 0);
        _install(NOSES, "NOSES");
        // one past the end, whatever the end currently is
        uint8 n = uint8(K.NOSES_COUNT);
        vm.expectRevert(abi.encodeWithSelector(FobalArtLibrary.PartOutOfRange.selector, n, n));
        lib.part(NOSES, n);
    }
}
