// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {FobalArtLibrary} from "../../src/FobalArtLibrary.sol";
import {SSTORE2} from "../../src/libraries/SSTORE2.sol";
import {IAccessControl} from "@openzeppelin/contracts/access/IAccessControl.sol";

/// THE P2 CLAIM: the bytes generated by packages/art/tools/gen-art.mjs decode
/// on-chain to exactly the rects the JS reference renderer draws from. The
/// fixtures read here are the SAME FILES the browser preview will load, so a
/// drift between preview and chain becomes a failing test rather than a
/// surprise after minting.
contract ArtLibraryTest is Test {
    FobalArtLibrary internal lib;
    address internal admin = makeAddr("admin");
    address internal bob = makeAddr("bob");

    bytes32 constant HAIR = bytes32("HAIR");
    bytes32 constant NOSES = bytes32("NOSES");

    function setUp() public {
        lib = new FobalArtLibrary(admin);
    }

    function _blob(string memory className) internal view returns (bytes memory) {
        string memory hexStr = vm.readFile(
            string.concat(vm.projectRoot(), "/../packages/art/gen/blobs/", className, ".hex")
        );
        return vm.parseBytes(vm.replace(hexStr, "\n", ""));
    }

    function _install(bytes32 key, string memory className) internal returns (bytes memory blob) {
        blob = _blob(className);
        vm.prank(admin);
        lib.setClass(key, blob);
    }

    // ------------------------------------------------- the cross-language proof

    function test_decodesGeneratedBytesToTheExactJsRects() public {
        _install(HAIR, "HAIR");
        assertEq(lib.partCount(HAIR), 24, "class size must match the generated constant");

        // HAIR[10] "Afro" — the JS reference decodes this to
        //   [[6,-1,20,10,4],[5,3,3,7,4],[24,3,3,7,4]]
        // and it is the case that proves NEGATIVE coordinates survive the bias.
        FobalArtLibrary.Rect[] memory afro = lib.part(HAIR, 10);
        assertEq(afro.length, 3, "afro rect count");
        assertEq(afro[0].x, int16(6));
        assertEq(afro[0].y, int16(-1));      // above the canvas, on purpose
        assertEq(afro[0].w, uint8(20));
        assertEq(afro[0].h, uint8(10));
        assertEq(afro[0].slot, uint8(4));
        assertEq(afro[1].x, int16(5));
        assertEq(afro[1].y, int16(3));
        assertEq(afro[2].x, int16(24));
        assertEq(afro[2].w, uint8(3));
        assertEq(afro[2].h, uint8(7));
    }

    function test_emptyPartDecodesToNoRects() public {
        _install(HAIR, "HAIR");
        assertEq(lib.part(HAIR, 0).length, 0, "HAIR[0] is Bald: no rects, not a revert");
    }

    function test_decodesASecondClassIndependently() public {
        _install(NOSES, "NOSES");
        assertEq(lib.partCount(NOSES), 3);
        FobalArtLibrary.Rect[] memory broad = lib.part(NOSES, 1);
        assertEq(broad.length, 2);
        assertEq(broad[0].x, int16(14));
        assertEq(broad[0].y, int16(16));
        assertEq(broad[0].w, uint8(4));
        assertEq(broad[1].x, int16(15));
        assertEq(broad[1].slot, uint8(2));
    }

    /// every part of every generated class must decode without reverting and
    /// stay inside sane bounds — the sweep that catches an encoder change
    function test_everyPartOfEveryClassDecodesInBounds() public {
        string[8] memory names =
            ["HEADS", "EYES", "BROWS", "NOSES", "MOUTHS", "BEARDS", "HAIR", "HEADWEAR"];
        uint256 totalRects;
        for (uint256 c; c < names.length; ++c) {
            bytes32 key = bytes32(bytes(names[c]));
            _install(key, names[c]);
            uint8 n = lib.partCount(key);
            assertGt(n, 0, names[c]);
            for (uint8 i; i < n; ++i) {
                FobalArtLibrary.Rect[] memory rs = lib.part(key, i);
                for (uint256 r; r < rs.length; ++r) {
                    assertGe(rs[r].x, int16(-32));
                    assertLe(rs[r].x, int16(64));
                    assertGe(rs[r].y, int16(-32));
                    assertLe(rs[r].y, int16(64));
                    assertGt(rs[r].w, uint8(0));
                    assertGt(rs[r].h, uint8(0));
                    assertLt(rs[r].slot, uint8(16));
                    ++totalRects;
                }
            }
        }
        emit log_named_uint("rects decoded across the whole atlas", totalRects);
        assertGt(totalRects, 200);
    }

    // ------------------------------------------------------------ storage

    function test_sstore2_roundTripsExactBytes() public {
        bytes memory blob = _blob("HAIR");
        address ptr = SSTORE2.write(blob);
        assertEq(SSTORE2.payloadLength(ptr), blob.length, "payload length");
        assertEq(keccak256(SSTORE2.read(ptr)), keccak256(blob), "bytes must survive verbatim");
        // and a window read matches the same window of the source
        bytes memory slice = SSTORE2.readSlice(ptr, 2, 8);
        for (uint256 i; i < 8; ++i) {
            assertEq(uint8(slice[i]), uint8(blob[2 + i]));
        }
    }

    function test_blobIsNotExecutable() public {
        address ptr = SSTORE2.write(_blob("NOSES"));
        (bool ok,) = ptr.call("");
        assertTrue(ok, "the STOP prefix means a call halts harmlessly");
    }

    // ------------------------------------------------- permanence + access

    function test_sealMakesAClassPermanent() public {
        _install(HAIR, "HAIR");
        vm.prank(admin);
        lib.seal(HAIR);
        assertTrue(lib.classInfo(HAIR).sealed_);
        vm.expectRevert(abi.encodeWithSelector(FobalArtLibrary.AlreadySealed.selector, HAIR));
        vm.prank(admin);
        lib.setClass(HAIR, _blob("HAIR"));
    }

    function test_unsealedClassCanBeRepointed_soReadBackHappensBeforeSealing() public {
        bytes memory blob = _blob("HAIR");
        vm.startPrank(admin);
        address first = lib.setClass(HAIR, blob);
        address second = lib.setClass(HAIR, blob);
        vm.stopPrank();
        assertTrue(first != second, "a fresh blob is deployed each time");
        assertEq(lib.classInfo(HAIR).pointer, second);
    }

    function test_onlyArtAdminCanWrite() public {
        bytes memory blob = _blob("NOSES");
        bytes memory err = abi.encodeWithSelector(
            IAccessControl.AccessControlUnauthorizedAccount.selector, bob, lib.ART_ADMIN_ROLE()
        );
        vm.startPrank(bob);
        vm.expectRevert(err);
        lib.setClass(NOSES, blob);
        vm.expectRevert(err);
        lib.seal(NOSES);
        vm.stopPrank();
    }

    function test_rejectsForeignBlobVersions() public {
        vm.startPrank(admin);
        vm.expectRevert(abi.encodeWithSelector(FobalArtLibrary.BadVersion.selector, uint8(9)));
        lib.setClass(HAIR, hex"0903");
        vm.stopPrank();
    }

    function test_unknownClassAndRangeErrors() public {
        vm.expectRevert(abi.encodeWithSelector(FobalArtLibrary.UnknownClass.selector, bytes32("NOPE")));
        lib.part(bytes32("NOPE"), 0);
        _install(NOSES, "NOSES");
        vm.expectRevert(abi.encodeWithSelector(FobalArtLibrary.PartOutOfRange.selector, uint8(3), uint8(3)));
        lib.part(NOSES, 3);
    }
}
