// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test, console} from "forge-std/Test.sol";
import {FobalArtLibrary} from "../../src/FobalArtLibrary.sol";
import {FobalFaceComposer} from "../../src/art/FobalFaceComposer.sol";
import {FobalKitComposer} from "../../src/art/FobalKitComposer.sol";
import {FobalRendererV2_1, IPlayerReader2} from "../../src/art/FobalRendererV2_1.sol";
import {FobalSquadRegistry} from "../../src/art/FobalSquadRegistry.sol";
import {FobalKitRegistry} from "../../src/art/FobalKitRegistry.sol";
import {FobalTraitEngine as TE} from "../../src/art/FobalTraitEngine.sol";
import {FobalArtConstants as K} from "../../src/art/FobalArtConstants.sol";
import {FobalAnchors} from "../../src/art/FobalAnchors.sol";

/// THE P3 CLAIM, and the only one that matters: for the same (dna,
/// appearance), the Solidity renderer emits the SAME BYTES as the JS
/// reference renderer in packages/art. Fixtures are generated by
/// tools/gen-art.mjs, so a change to either implementation that is not
/// mirrored in the other fails this test.
contract RendererParityTest is Test {
    FobalArtLibrary internal art;
    FobalRendererV2_1 internal renderer;
    address internal admin = makeAddr("admin");

    string[13] internal CLASSES =
        ["HEADS", "SHADING", "EARS", "EYES", "BROWS", "NOSES", "MOUTHS", "BEARDS", "HAIR", "HEADWEAR", "NECKS", "BUILDS", "COLLARS"];

    bytes32[] internal fxDna;
    uint256[] internal fxAppearance;
    bytes32[] internal fxSvgHash;
    uint256[] internal fxKitPrimary;
    uint256[] internal fxKitSecondary;
    uint256[] internal fxKitAccent;
    uint256[] internal fxKitPattern;
    bytes32[] internal fxSvgKitHash;
    uint256[] internal fxPosition;

    /// @dev the free-agent kit the reference derives for this identity
    function _render(uint256 i) internal view returns (string memory) {
        return renderer.imageWithKit(
            fxDna[i], fxAppearance[i], renderer.freeAgentKit(TE.seedOf(fxDna[i], fxAppearance[i]), uint8(fxPosition[i]))
        );
    }
    function _renderDna(bytes32 dna, uint256 appearance) internal view returns (string memory) {
        return renderer.imageWithKit(dna, appearance, renderer.freeAgentKit(TE.seedOf(dna, appearance), 2));
    }

    function setUp() public {
        art = new FobalArtLibrary(admin);
        vm.startPrank(admin);
        for (uint256 i; i < CLASSES.length; ++i) {
            art.setClass(bytes32(bytes(CLASSES[i])), _blob(CLASSES[i]));
        }
        vm.stopPrank();
        // imageWithKit() renders from identity plus an EXPLICIT kit and
        // never reads a registry, which is what makes it the parity entry
        // point. The renderer under test is the one that actually deploys —
        // a second, simpler renderer kept only for this test was itself a
        // place for the two implementations to drift apart.
        renderer = new FobalRendererV2_1(
            IPlayerReader2(address(0)),
            new FobalFaceComposer(art),
            new FobalKitComposer(),
            FobalSquadRegistry(address(0)),
            FobalKitRegistry(address(0))
        );

        string memory json = vm.readFile(
            string.concat(vm.projectRoot(), "/../packages/art/gen/fixtures/render.json")
        );
        fxDna = vm.parseJsonBytes32Array(json, ".dna");
        fxAppearance = vm.parseJsonUintArray(json, ".appearance");
        fxSvgHash = vm.parseJsonBytes32Array(json, ".svgHash");
        fxKitPrimary = vm.parseJsonUintArray(json, ".kitPrimary");
        fxKitSecondary = vm.parseJsonUintArray(json, ".kitSecondary");
        fxKitAccent = vm.parseJsonUintArray(json, ".kitAccent");
        fxKitPattern = vm.parseJsonUintArray(json, ".kitPattern");
        fxSvgKitHash = vm.parseJsonBytes32Array(json, ".svgKitHash");
        fxPosition = vm.parseJsonUintArray(json, ".position");
    }

    function _blob(string memory className) internal view returns (bytes memory) {
        string memory h = vm.readFile(
            string.concat(vm.projectRoot(), "/../packages/art/gen/blobs/", className, ".hex")
        );
        return vm.parseBytes(vm.replace(h, "\n", ""));
    }

    /// Every fixture seed, byte for byte.
    function test_svgIsByteIdenticalToTheJsReference() public view {
        // NOT a hardcoded count. The generator extends the base set until
        // every part index of every class is rendered — pinning 64 here would
        // fight the coverage sweep every time the atlas changes.
        assertGe(fxDna.length, 64, "fixture set");
        assertEq(fxPosition.length, fxDna.length, "every fixture carries a position");
        uint256 matched;
        for (uint256 i; i < fxDna.length; ++i) {
            string memory svg = _render(i);
            assertEq(
                keccak256(bytes(svg)),
                fxSvgHash[i],
                string.concat("SVG differs from the JS reference at fixture ", vm.toString(i))
            );
            ++matched;
        }
        assertEq(matched, fxDna.length);
    }

    /// @dev diagnostic: `forge test --mt test_dumpFixtureZero -vv` prints the
    /// chain's bytes so they can be diffed against the JS reference directly.
    function test_dumpFixtureZero() public view {
        console.log(_render(0));
    }

    function test_renderIsDeterministic() public view {
        for (uint256 i; i < 8; ++i) {
            assertEq(
                keccak256(bytes(_render(i))),
                keccak256(bytes(_render(i)))
            );
        }
    }

    /// The goalkeeper's free-agent kit existed only in the JS reference: the
    /// browser previewed a gold keeper the chain would never have minted.
    /// Some fixture must actually render position 0, or porting it proves
    /// nothing.
    function test_fixturesExerciseTheGoalkeeperPath() public view {
        uint256 keepers;
        for (uint256 i; i < fxPosition.length; ++i) {
            if (fxPosition[i] == 0) ++keepers;
        }
        assertGt(keepers, 0, "no fixture renders a goalkeeper");
        FobalKitComposer.Kit memory gk = renderer.freeAgentKit(bytes32(uint256(1)), 0);
        FobalKitComposer.Kit memory outfield = renderer.freeAgentKit(bytes32(uint256(1)), 2);
        assertTrue(gk.primary != outfield.primary, "a free-agent keeper must not look like an outfielder");
    }

    /// A club's registered keeper strip must WIN over the free-agent colours —
    /// the JS override used to repaint an explicit kit gold.
    function test_anExplicitKitBeatsTheKeeperFallback() public view {
        FobalKitComposer.Kit memory club = FobalKitComposer.Kit(0xc8322b, 0x1b1b1f, 0xf2f4f8, 1);
        assertEq(
            keccak256(bytes(renderer.imageWithKit(fxDna[0], fxAppearance[0], club))),
            keccak256(bytes(renderer.imageWithKit(fxDna[0], fxAppearance[0], club))),
            "an explicit kit renders the same regardless of anything else"
        );
    }

    /// Identity is a pure function of (dna, appearance): nothing else can
    /// change a face — not the token id, not the caller, not the block.
    function test_identityDependsOnlyOnDnaAndAppearance() public {
        bytes32 a = keccak256(bytes(_render(0)));
        vm.warp(block.timestamp + 30 days);
        vm.roll(block.number + 5000);
        vm.prank(makeAddr("someone-else"));
        bytes32 b = keccak256(bytes(_render(0)));
        assertEq(a, b, "a face must not depend on time, block or caller");
    }

    function test_differentSeedsRenderDifferently() public view {
        uint256 distinct;
        bytes32[] memory seen = new bytes32[](fxDna.length);
        for (uint256 i; i < fxDna.length; ++i) {
            bytes32 h = keccak256(bytes(_render(i)));
            bool dup;
            for (uint256 j; j < distinct; ++j) {
                if (seen[j] == h) dup = true;
            }
            if (!dup) seen[distinct++] = h;
        }
        assertEq(distinct, fxDna.length, "every fixture seed must render a distinct player");
    }

    /// A trait engine that reverts would take tokenURI down for that token,
    /// so it must resolve for ANY input, including adversarial ones.
    function testFuzz_traitsAlwaysResolve(bytes32 dna, uint256 appearance) public pure {
        TE.Traits memory t = TE.traitsOf(TE.seedOf(dna, appearance));
        assertLt(t.head, 6);
        assertLt(t.hair, 21);
        assertLt(t.headwear, 6);
        assertLt(t.beard, 8);
        assertLt(t.eyes, 6);
        assertLt(t.brows, 6);
        assertLt(t.nose, 7);
        assertLt(t.mouth, 7);
        assertLt(t.ears, 3);
        assertLt(t.build, 4);
        assertLt(t.collar, 4);
        assertLt(t.neck, 3);
        assertLt(t.shading, 6);
        assertLt(t.skin, 8);
        assertLt(t.bg, 8);
    }

    function testFuzz_renderNeverRevertsForAnyIdentity(bytes32 dna, uint256 appearance) public view {
        string memory svg = _renderDna(dna, appearance);
        assertGt(bytes(svg).length, 200, "every identity must produce a real image");
    }

    /// The constraint pass must hold on chain exactly as it does in JS.
    function testFuzz_constraintsHold(bytes32 dna, uint256 appearance) public pure {
        TE.Traits memory t = TE.traitsOf(TE.seedOf(dna, appearance));
        uint256 bit = 1 << t.headwear;
        if (bit & K.HEADWEAR_COVERS_MASK != 0) {
            // the rule is no longer "index below ten" — it is that a covered
            // head wears a style the fallback map considers a FIXED POINT,
            // so the mapping is idempotent and can never chain
            assertEq(t.hair, uint8(K.HAIR_FALLBACK[t.hair]), "hair under a hat must be a fallback fixed point");
        }
        if (t.hair == 0) assertEq(bit & K.HEADWEAR_BAND_MASK, 0, "a bald head cannot wear a band");
        if (t.beard >= 6) {
            assertTrue(t.mouth != 4, "no shouting inside a full beard");
            assertTrue(t.collar != 3, "a long beard cannot sit on a polo collar");
        }
        // the geometry correlation must survive the constraint pass: whatever
        // mouth comes out the far end must still be legal on this skull
        uint8 wc = FobalAnchors.anchorsOf(t.head).widthClass;
        bytes memory lens = K.MOUTH_ELIG_LEN;
        bytes memory elig = K.MOUTH_ELIG;
        uint256 start;
        for (uint256 k; k < wc; ++k) start += uint256(uint8(lens[k]));
        bool legal;
        for (uint256 k; k < uint256(uint8(lens[wc])); ++k) {
            if (uint8(elig[start + k]) == t.mouth) legal = true;
        }
        assertTrue(legal, "the constraint pass must not undo the width rule");
    }
}
