// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {FobalArtLibrary} from "../../src/FobalArtLibrary.sol";
import {FobalFaceComposer} from "../../src/art/FobalFaceComposer.sol";
import {FobalRendererV2, IPlayerReader} from "../../src/art/FobalRendererV2.sol";
import {FobalTraitEngine as TE} from "../../src/art/FobalTraitEngine.sol";

/// THE P3 CLAIM, and the only one that matters: for the same (dna,
/// appearance), the Solidity renderer emits the SAME BYTES as the JS
/// reference renderer in packages/art. Fixtures are generated by
/// tools/gen-art.mjs, so a change to either implementation that is not
/// mirrored in the other fails this test.
contract RendererV2ParityTest is Test {
    FobalArtLibrary internal art;
    FobalRendererV2 internal renderer;
    address internal admin = makeAddr("admin");

    string[8] internal CLASSES = ["HEADS", "EYES", "BROWS", "NOSES", "MOUTHS", "BEARDS", "HAIR", "HEADWEAR"];

    bytes32[] internal fxDna;
    uint256[] internal fxAppearance;
    bytes32[] internal fxSvgHash;

    function setUp() public {
        art = new FobalArtLibrary(admin);
        vm.startPrank(admin);
        for (uint256 i; i < CLASSES.length; ++i) {
            art.setClass(bytes32(bytes(CLASSES[i])), _blob(CLASSES[i]));
        }
        vm.stopPrank();
        // imageOf() renders from identity alone and never reads the
        // collection, which is exactly what makes it the parity entry point
        renderer = new FobalRendererV2(IPlayerReader(address(0)), new FobalFaceComposer(art));

        string memory json = vm.readFile(
            string.concat(vm.projectRoot(), "/../packages/art/gen/fixtures/render.json")
        );
        fxDna = vm.parseJsonBytes32Array(json, ".dna");
        fxAppearance = vm.parseJsonUintArray(json, ".appearance");
        fxSvgHash = vm.parseJsonBytes32Array(json, ".svgHash");
    }

    function _blob(string memory className) internal view returns (bytes memory) {
        string memory h = vm.readFile(
            string.concat(vm.projectRoot(), "/../packages/art/gen/blobs/", className, ".hex")
        );
        return vm.parseBytes(vm.replace(h, "\n", ""));
    }

    /// Every fixture seed, byte for byte.
    function test_svgIsByteIdenticalToTheJsReference() public view {
        assertEq(fxDna.length, 64, "fixture set");
        uint256 matched;
        for (uint256 i; i < fxDna.length; ++i) {
            string memory svg = renderer.imageOf(fxDna[i], fxAppearance[i]);
            assertEq(
                keccak256(bytes(svg)),
                fxSvgHash[i],
                string.concat("SVG differs from the JS reference at fixture ", vm.toString(i))
            );
            ++matched;
        }
        assertEq(matched, 64);
    }

    function test_renderIsDeterministic() public view {
        for (uint256 i; i < 8; ++i) {
            assertEq(
                keccak256(bytes(renderer.imageOf(fxDna[i], fxAppearance[i]))),
                keccak256(bytes(renderer.imageOf(fxDna[i], fxAppearance[i])))
            );
        }
    }

    /// Identity is a pure function of (dna, appearance): nothing else can
    /// change a face — not the token id, not the caller, not the block.
    function test_identityDependsOnlyOnDnaAndAppearance() public {
        bytes32 a = keccak256(bytes(renderer.imageOf(fxDna[0], fxAppearance[0])));
        vm.warp(block.timestamp + 30 days);
        vm.roll(block.number + 5000);
        vm.prank(makeAddr("someone-else"));
        bytes32 b = keccak256(bytes(renderer.imageOf(fxDna[0], fxAppearance[0])));
        assertEq(a, b, "a face must not depend on time, block or caller");
    }

    function test_differentSeedsRenderDifferently() public view {
        uint256 distinct;
        bytes32[] memory seen = new bytes32[](fxDna.length);
        for (uint256 i; i < fxDna.length; ++i) {
            bytes32 h = keccak256(bytes(renderer.imageOf(fxDna[i], fxAppearance[i])));
            bool dup;
            for (uint256 j; j < distinct; ++j) {
                if (seen[j] == h) dup = true;
            }
            if (!dup) seen[distinct++] = h;
        }
        assertEq(distinct, fxDna.length, "every fixture seed must render a distinct player");
    }

    /// A trait engine that reverts would take tokenURI down for that token,
    /// so it must resolve for ANY input, including adversarial ones.
    function testFuzz_traitsAlwaysResolve(bytes32 dna, uint256 appearance) public pure {
        TE.Traits memory t = TE.traitsOf(TE.seedOf(dna, appearance));
        assertLt(t.head, 6);
        assertLt(t.hair, 24);
        assertLt(t.headwear, 10);
        assertLt(t.beard, 8);
        assertLt(t.skin, 8);
        assertLt(t.bg, 8);
    }

    function testFuzz_renderNeverRevertsForAnyIdentity(bytes32 dna, uint256 appearance) public view {
        string memory svg = renderer.imageOf(dna, appearance);
        assertGt(bytes(svg).length, 200, "every identity must produce a real image");
    }

    /// The constraint pass must hold on chain exactly as it does in JS.
    function testFuzz_constraintsHold(bytes32 dna, uint256 appearance) public pure {
        TE.Traits memory t = TE.traitsOf(TE.seedOf(dna, appearance));
        uint256 bit = 1 << t.headwear;
        // 760 = covers mask, 262 = band mask (generated constants)
        if (bit & 760 != 0) assertLt(t.hair, 10, "big hair cannot sit under a hat");
        if (t.hair == 0) assertEq(bit & 262, 0, "a bald head cannot wear a band");
        if (t.beard >= 6) assertTrue(t.mouth != 8, "no shouting inside a full beard");
    }
}
