// The web preview and the chain must draw the same player.
//
// Before P5 there were THREE avatar implementations: the Solidity renderer,
// a hand-maintained "faithful port" in the browser, and a third inside the
// golden client. The hand port had already drifted — it invented a goalkeeper
// kit the chain never had, and masked appearance to 24 bits so no accessory
// could ever appear — while onboarding told users they were seeing "the exact
// art the chain mints".
//
// apps/web/public/js/avatar.js is now GENERATED from the same spec, and this
// test is what stops it drifting again: it compares the browser module's
// bytes to the reference renderer that the Solidity is proven byte-identical
// against (contracts/test/unit/RendererV2Parity.t.sol). The chain, the
// reference and the browser are therefore one implementation in three places.
import { describe, expect, test } from 'vitest';
import { readFileSync } from 'node:fs';
// @ts-expect-error — generated ES module, no types
import { avatarSvgOnchain, avatarSvgDressed, traitsOf, seedOf } from '../public/js/avatar.js';
// @ts-expect-error — the reference renderer
import { renderPlayer, traitsOf as refTraits, seedOf as refSeed } from '../../../packages/art/src/render.js';

const FIXTURES = JSON.parse(
  readFileSync(new URL('../../../packages/art/gen/fixtures/render.json', import.meta.url), 'utf8'),
);

describe('browser avatar == reference renderer', () => {
  test('free-agent rendering is byte-identical across the fixture set', () => {
    for (let i = 0; i < FIXTURES.dna.length; i++) {
      const dna = FIXTURES.dna[i];
      const appearance = BigInt(FIXTURES.appearance[i]);
      expect(avatarSvgOnchain({ dna, appearance }), `fixture ${i}`)
        .toBe(renderPlayer({ dna, appearance }));
    }
  });

  test('club-kit rendering is byte-identical too', () => {
    for (let i = 0; i < FIXTURES.dna.length; i++) {
      const dna = FIXTURES.dna[i];
      const appearance = BigInt(FIXTURES.appearance[i]);
      const kit = {
        primary: Number(FIXTURES.kitPrimary[i]).toString(16).padStart(6, '0'),
        secondary: Number(FIXTURES.kitSecondary[i]).toString(16).padStart(6, '0'),
        accent: Number(FIXTURES.kitAccent[i]).toString(16).padStart(6, '0'),
        pattern: Number(FIXTURES.kitPattern[i]),
      };
      expect(avatarSvgDressed({ dna, appearance }, kit), `fixture ${i}`)
        .toBe(renderPlayer({ dna, appearance, kit }));
    }
  });

  /** The browser inlines its own keccak; if it diverged, traits would differ
   *  silently and the preview would show a different footballer. */
  test('the inlined keccak derives the same seed and traits', () => {
    for (let i = 0; i < 32; i++) {
      const dna = FIXTURES.dna[i];
      const appearance = BigInt(FIXTURES.appearance[i]);
      expect(Array.from(seedOf(dna, appearance))).toEqual(Array.from(refSeed(dna, appearance)));
      expect(traitsOf(seedOf(dna, appearance))).toEqual(refTraits(refSeed(dna, appearance)));
    }
  });

  /** These hashes are what the SOLIDITY test asserts against, so matching
   *  them here chains browser -> reference -> chain into one guarantee. */
  test('the browser matches the hashes the Solidity test uses', async () => {
    const { keccak_256 } = await import('@noble/hashes/sha3');
    const hex = (s: string) => '0x' + [...keccak_256(new TextEncoder().encode(s))]
      .map(b => b.toString(16).padStart(2, '0')).join('');
    for (let i = 0; i < FIXTURES.dna.length; i++) {
      expect(hex(avatarSvgOnchain({
        dna: FIXTURES.dna[i],
        appearance: BigInt(FIXTURES.appearance[i]),
        position: Number(FIXTURES.position[i]),
      }))).toBe(FIXTURES.svgHash[i]);
    }
  });

  test('the generated module is not hand-edited', () => {
    const src = readFileSync(new URL('../public/js/avatar.js', import.meta.url), 'utf8');
    expect(src).toContain('GENERATED by packages/art/tools/gen-art.mjs');
    expect(src).toContain('DO NOT EDIT');
  });
});
