// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";
import {SSTORE2} from "./libraries/SSTORE2.sol";

/// @title FobalArtLibrary — the on-chain art atlas.
/// @notice Holds pointers to SSTORE2 blobs of authored part data and decodes
/// them into rects for a composer. The blob format is generated by
/// packages/art/tools/gen-art.mjs and proven byte-identical by the parity
/// harness, so the browser preview and the chain draw from the same bytes.
///
///   blob := [version:1][partCount:1][offset:2 x N][parts...]
///   part := [rectCount:1][rect x 5]
///   rect := [x+BIAS][y+BIAS][w][h][paletteSlot]
///
/// Coordinates are biased because parts legitimately draw outside the frame
/// (an afro starts above the canvas). Once `seal()` is called a class can
/// never be repointed — art becomes as immutable as bytecode, which is the
/// property that makes "fully on-chain" mean something.
contract FobalArtLibrary is AccessControl {
    bytes32 public constant ART_ADMIN_ROLE = keccak256("ART_ADMIN_ROLE");

    uint8 public constant BLOB_VERSION = 1;
    int256 public constant BIAS = 32;

    struct ClassInfo {
        address pointer;
        uint8 partCount;
        bool sealed_;
    }

    /// @dev keyed by a short class name: "HAIR", "HEADS", ...
    mapping(bytes32 className => ClassInfo) private _classes;

    event ClassSet(bytes32 indexed className, address indexed pointer, uint8 partCount);
    event ClassSealed(bytes32 indexed className, address indexed pointer);

    error AlreadySealed(bytes32 className);
    error UnknownClass(bytes32 className);
    error BadVersion(uint8 found);
    error PartOutOfRange(uint8 index, uint8 count);

    struct Rect {
        int16 x;
        int16 y;
        uint8 w;
        uint8 h;
        uint8 slot;
    }

    constructor(address admin) {
        _grantRole(DEFAULT_ADMIN_ROLE, admin);
        _grantRole(ART_ADMIN_ROLE, admin);
    }

    /// @notice Write a class's blob and point at it. Verify by read-back
    /// BEFORE sealing — a sealed class is permanent.
    function setClass(bytes32 className, bytes calldata blob) external onlyRole(ART_ADMIN_ROLE) returns (address ptr) {
        ClassInfo storage info = _classes[className];
        if (info.sealed_) revert AlreadySealed(className);
        if (blob.length < 2) revert BadVersion(0);
        if (uint8(blob[0]) != BLOB_VERSION) revert BadVersion(uint8(blob[0]));
        ptr = SSTORE2.write(blob);
        info.pointer = ptr;
        info.partCount = uint8(blob[1]);
        emit ClassSet(className, ptr, info.partCount);
    }

    /// @notice Make a class permanent. There is deliberately no unseal.
    function seal(bytes32 className) external onlyRole(ART_ADMIN_ROLE) {
        ClassInfo storage info = _classes[className];
        if (info.pointer == address(0)) revert UnknownClass(className);
        info.sealed_ = true;
        emit ClassSealed(className, info.pointer);
    }

    function classInfo(bytes32 className) external view returns (ClassInfo memory) {
        return _classes[className];
    }

    function partCount(bytes32 className) external view returns (uint8) {
        return _classes[className].partCount;
    }

    /// @notice Decode one part into rects. Two EXTCODECOPY reads: the header
    /// window for the offset, then the part body — never the whole blob.
    function part(bytes32 className, uint8 index) external view returns (Rect[] memory rects) {
        ClassInfo storage info = _classes[className];
        address ptr = info.pointer;
        if (ptr == address(0)) revert UnknownClass(className);
        if (index >= info.partCount) revert PartOutOfRange(index, info.partCount);

        bytes memory head = SSTORE2.readSlice(ptr, 2 + uint256(index) * 2, 2);
        uint256 off = (uint256(uint8(head[0])) << 8) | uint256(uint8(head[1]));

        bytes memory countByte = SSTORE2.readSlice(ptr, off, 1);
        uint256 n = uint8(countByte[0]);
        if (n == 0) return new Rect[](0);

        bytes memory body = SSTORE2.readSlice(ptr, off + 1, n * 5);
        rects = new Rect[](n);
        for (uint256 i; i < n; ++i) {
            uint256 p = i * 5;
            rects[i] = Rect({
                x: int16(int256(uint256(uint8(body[p]))) - BIAS),
                y: int16(int256(uint256(uint8(body[p + 1]))) - BIAS),
                w: uint8(body[p + 2]),
                h: uint8(body[p + 3]),
                slot: uint8(body[p + 4])
            });
        }
    }
}
